<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_JoystickToCartesianVelocity" Id="{ae366a50-de77-43a3-9b65-9305738275e4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_JoystickToCartesianVelocity
VAR_INPUT
	fNormalizezJoistick : LREAL;
	fScalingFactor : LREAL; 
END_VAR
VAR_OUTPUT
	fAxisVelocity : LREAL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[

fAxisVelocity := fNormalizezJoistick*fScalingFactor;]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>